"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
import math, sys

def isPentagonal(n):
	x = (math.sqrt(24 * n + 1) + 1)/6;
	return math.floor(x) == math.ceil(x);

def isHexagonal(k):
	n = (math.sqrt(8 * k + 1) + 1) / 4;
	return n == round(n)

def getPentagonal(num):
	n = 1
	start = 1
	for x in range(start,start + num):
		yield x*(3*x-1)/2

def getHexagonal(num):
	n = 1
	start = 1
	for x in range(start,start + num):
		yield x*(2*x-1)

def getTriangle(num):
	n = 1
	start = 1
	for x in range(start,start + num):
		yield x*(x+1)/2


for x in getTriangle(100000):
	if isPentagonal(x) and isHexagonal(x):
		print x
