"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

import math, time

ti = time.time()

def getdivisorscount(n):
    divisors = []
    topbound = int(math.sqrt(n))
    for i in range(1,topbound):
        if n % i == 0:
            divisors.append(i)
            divisors.append(n / i)
    if math.sqrt(n) == topbound:
        divisors.append(topbound)
    return len(divisors)

def gettriangle(n):
    return (n * (n + 1)) / 2


go = True    
incr = 1
maxdivisors = 500
while go:
    triangle = gettriangle(incr)
    divisorscount = getdivisorscount(triangle)
    if divisorscount >= maxdivisors:
        print "incr %d triangle %d dcount %d" % (incr, triangle, divisorscount)
        go = False
    incr += 1

print "Time taken(secs):", time.time() - ti
        
